### ISSUE TITLE
Revisit temperature limits and report over/under-temp load shutdown correctly

### ISSUE THREAD

**Issue by martinjaeger** [LibreSolar/charge-controller-firmware#59]
If the measured battery temperature gets above 50°C (configurable setting), discharging of the battery is disabled. The load output only realizes that it is not allowed to discharge anymore and assumes it is because of low voltage, so it goes into `LOAD_STATE_OFF_LOW_SOC` state. This does not make much sense.

Related to this issue: If no external sensor is connected, the sensor on the charge controller PCB is used, which can get considerably much hotter than ambient temperature at high load. This should be considered, either by a model-based approach or something more simple that increases the limits if charge controller load is high.

**Comment by hogthrob** [comment]
Well, main issue: easiest thing would be to rename LOAD_STATE_OFF_LOW_SOC to LOAD_STATE_OFF_BAT_PROTECT which applies to both cases. 

The temp thing:
Is there any general correlation between the charge controller temp sensor's temperature and the battery temperature? If the battery is separated from the charge controller, the answer is probably: no. If the charge controller is mounted in thermal proximity of the battery, the answer is probably: yes sometimes. 
In addition we have the load issue which is unrelated to the battery's state itself. If the battery is large enough, even a high load (which causes high controller temperature) may not bother the battery at all.  

To cover the different cases best with overcomplicating things I think we should give the controller's temperature sensor a separate (configurable) limit meant to be used to protect the board from issues due to overheating (i.e. to reduce load). And the battery temp sensor is used if present, otherwise no battery temperature monitoring occurs and the respective limits are simply not used.

**Comment by JordanSilverman** [comment]
Interesting! I personally think that the temperature measurement from inside the casing is equally as interesting as the battery temperature. But you are right, the measurement does not reflect what it's supposed to.

**Comment by martinjaeger** [comment]
Yes, we can keep the internal temperature measurement and send it out if needed, but it shouldn't be called battery temperature :)

**Comment by JordanSilverman** [comment]
So should we be setting different limits for the internal and external temperatures separately?
~80°C for internal
Stay with 50°C for external

**Comment by JordanSilverman** [comment]
Nice idea. I still think we should keep those limits quite high for those hot countries.
